
var Bigmap= undefined;
var startLat = 38.883845;
var startLng = -94.667995;

//Make a model template so that the model an get the information from third party apis
//{lat:"", lng:"", markerName?:""}

//this is the global array so we can access it. This may later be put in the model where all the data should be held

var MarkerArray = ko.observableArray([
	   {lat: "38.895180" , lng:"-94.669989", markerName:"HR HAVEN" }
	    ]);

var Model = {
	//init: function(){
	  //populate and build the marker Array which will be used to place markers
	  //var MarkerArray = ko.observablearray([
	   //{lat: "38.895180" , lng:"-94.669989", markerName:"HR HAVEN" }
	    //]);
	    
	 passData: function(){
	   return MarkerArray();
	   //console.log(MarkerArray()[0].lat); //Super fucking important, its a function, not an object
	   
	 },
	 helloWorld: function(){
	   console.log("HelloWorld");
	 }
};


//locations View
//Search and Filter Locations here
//At least 5 locations
//lets make this the top bar
//Text area here to filter markers that already show up
//Search function will not be enough through 3rd party API, must filter myself
//knockout needs to handle List, Filter, and any other information subject to changing state.

locationView = {

};

// Maps View
//Display Map Markers for Places of interest within this neighborhood
//additionall functionality to animate map markers
//open information window from 3rd party APIS

mapView = {

	init: function (){
		

		//initialize Map.
		 var map = new google.maps.Map(document.getElementById('domMap'),{
			center: {lat: startLat, lng: startLng},
			scrollwheel: true,
			zoom: 12
		});
		
		Bigmap=map; //set this new map we made to be used as a global variable
    console.log(Bigmap);
    
		//For Funsies, make a rough polygon for OP
		//alt: make circles and use that to look for stoes/whatever in that radius

		//TODO, make this whole thing into a function for a handler
		////////////////
		var startMarker = new google.maps.Marker({
			position: {lat: startLat, lng: startLng},
			map: map,
			title: 'startLoc',
			//code to store this in an Array
		});
		var infowindow = new google.maps.InfoWindow({
			content: '135th and Metcalf' //this can be super complicated, its a full popup window
		});

		startMarker.addListener('click', function(){
			infowindow.open(map, startMarker);
			//center on location
		});
		//////////////////
		//////////////////

		console.log("initilized");
	},
	//resize WIP
	resize: function(){
		var mapDiv =document.getElementById("domMap");
		mapDiv.style.width = 80%
		google.maps.event.trigger(Bigmap, "resize"); //resize the map, BigMap should be our map reference
		console.log("mapDiv");
	},
	///////PLACE MAP MARKERS////////////
	///////////////////////////////////
	placeMapMarkers: function(){
		//code to retrieve data from Model and then place it in here
		//code to place markers at each location of interest
		
		//foreach data in model(){
		var startMarker = new google.maps.Marker({
			position: {lat: marker.lat, lng: marker.lng}, //marker.lat, and marker.lng will be generated by the model
			map: map,
			title: '%generated name',
			//code to store this in an Array
		});
		
		//data for the popup on the Location
		var infowindow = new google.maps.InfoWindow({
			content: '135th and Metcalf' //this can be super complicated, its a full popup window
		});
    //click event for each marker
		startMarker.addListener('click', function(){
			infowindow.open(map, startMarker);
			//center on location
		});
		
	},
	clearMapMarkers: function(){
		//code to remove all map markers
		//https://developers.google.com/maps/documentation/javascript/examples/marker-remove
		//clearMarkers();
		//empty the array
	},
	popupMarker: function(){ //will pass in data in here from VM
		//code to generate a popup over selected target
	}
}

	//My Google Maps API Key:  AIzaSyACeu3Nlk0hCOlOHFX0bKVc5m2gFrcNTiQ


//ViewModel
 
 ViewModel= {
  
  //this one will grab info from the Model Array to build makers
  //name can be changed later to avoid confusion
  
   buildMarker: function(lat,lng,mName){
     
     //for the position array, make your own and fill in the data
     
      var newMarker = new google.maps.Marker({
			position: {lat: lat, lng: lng}, //VMlat, VMlng from Model
			map: Bigmap,
			title: mName,
		  });
		  
		  var newInfoWin = new google.maps.InfoWindow({
			content: mName, //this can be super complicated, its a full popup window
		  });
	    
	    console.log("BuildMarker");
	    //newMarker.addListener('click', function(){
	      //newInfoWin.open(map, newMarker);
	    //});
    },
  
  
  init: function(){
    
    var localArray= Model.passData(); //Get the Model
  
    for (i = 0; i < localArray.length; i++) {
      var nlat=localArray[i].lat;
      var nlng=localArray[i].lng;
      var nName=localArray[i].markerName;
      
      var testlat=nlat;
      var testlng=nlng;
      
      console.log(i);
      console.log(nlat);
      console.log(nlng);
      
      ViewModel.buildMarker(testlat,testlng,nName);
    }
  }

 };
 

